"""Generator behaviour.

The generator is the foundation of every number this project reports. If it is wrong,
the metrics are wrong in a way that looks like success — a matcher tuned against a
broken generator scores beautifully and means nothing.

So these tests check three separate things:

1. **Reproducibility.** A seed must reproduce byte-identical files, or no published
   figure can be regenerated by a reviewer.
2. **Arithmetic honesty.** Settlement amounts must come from the real fee model, not
   from something approximate that happens to be matchable.
3. **Truth integrity.** Every bank credit is accounted for in ground truth, and every
   truth link resolves to rows that actually exist.
"""

from __future__ import annotations

import csv
import hashlib
import itertools
from pathlib import Path

import pytest

from ledgerloop.generate.chaos import ADVERSARIAL, EASY, REALISTIC, ChaosFlag, ChaosProfile
from ledgerloop.generate.fee_model import DEFAULT_FEE_MODEL
from ledgerloop.generate.synth import (
    GeneratedBatch,
    LinkType,
    generate_batch,
    generate_fixture,
    write_batch,
)
from ledgerloop.ingest.schemas import BankRow, InvoiceRow, SettlementRow

#: Keys `write_batch` must return. Pinning these is the point: the CLI iterates this
#: mapping rather than naming the ground-truth file, which is what keeps `cli.py`
#: clear of the tokens `tests/test_no_truth_leak.py` forbids.
EXPECTED_OUTPUT_KEYS = {"invoices", "settlements", "bank_statement", "truth"}

SETTLEMENT_COUNT = 60


def _batch(profile: ChaosProfile = REALISTIC, *, seed: int = 42) -> GeneratedBatch:
    return generate_batch(settlements=SETTLEMENT_COUNT, seed=seed, profile=profile)


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


# --- reproducibility ------------------------------------------------------------


def test_same_seed_reproduces_byte_identical_files(tmp_path: Path) -> None:
    """§5.6. Without this, no published number can be reproduced from the repo."""
    first = write_batch(_batch(seed=42), tmp_path / "a")
    second = write_batch(_batch(seed=42), tmp_path / "b")

    assert set(first) == EXPECTED_OUTPUT_KEYS
    assert set(second) == EXPECTED_OUTPUT_KEYS
    for key in EXPECTED_OUTPUT_KEYS:
        assert _sha256(first[key]) == _sha256(second[key]), f"{key} not byte-identical"


def test_different_seed_produces_different_data(tmp_path: Path) -> None:
    """Guards the guard: a generator that ignores its seed would pass the test above."""
    first = write_batch(_batch(seed=42), tmp_path / "a")
    second = write_batch(_batch(seed=43), tmp_path / "b")

    assert _sha256(first["settlements"]) != _sha256(second["settlements"])


def test_written_files_use_lf_line_endings(tmp_path: Path) -> None:
    """Development is on Windows, CI is Linux. An unpinned line terminator makes
    'byte-identical' true locally and false in CI, which is the worst way to find out."""
    for path in write_batch(_batch(), tmp_path).values():
        assert b"\r\n" not in path.read_bytes(), f"{path.name} has CRLF line endings"


# --- shape and schema -----------------------------------------------------------


def test_settlement_count_matches_requested_records() -> None:
    """`--records` counts settlements: the entity actually being reconciled."""
    assert len(_batch().settlements) == SETTLEMENT_COUNT


def test_every_generated_row_validates_against_the_ingest_schemas() -> None:
    """The generator must not emit anything ingest would quarantine."""
    batch = _batch(ADVERSARIAL)
    for invoice in batch.invoices:
        InvoiceRow.model_validate(invoice.model_dump())
    for settlement in batch.settlements:
        SettlementRow.model_validate(settlement.model_dump())
    for bank_txn in batch.bank_txns:
        BankRow.model_validate(bank_txn.model_dump())


def test_all_money_fields_are_integer_paise() -> None:
    """Design rule 5. A float here is a defect, not a style preference."""
    batch = _batch(ADVERSARIAL)
    money_fields = [
        (row, name)
        for rows, names in (
            (batch.invoices, ["invoice_amount_paise"]),
            (
                batch.settlements,
                [
                    "gross_amount_paise",
                    "fee_paise",
                    "gst_on_fee_paise",
                    "tds_paise",
                    "net_amount_paise",
                ],
            ),
            (batch.bank_txns, ["credit_paise", "debit_paise", "balance_paise"]),
        )
        for row in rows
        for name in names
    ]
    for row, name in money_fields:
        value = getattr(row, name)
        assert type(value) is int, f"{type(row).__name__}.{name} is {type(value).__name__}"


def test_bank_statement_has_no_structured_reference_column(tmp_path: Path) -> None:
    """§5.3. The absence of a reference field *is* the problem this project solves.
    A future contributor making the generator 'easier' would break the premise."""
    bank_file = write_batch(_batch(), tmp_path)["bank_statement"]
    with bank_file.open(newline="") as handle:
        header = next(csv.reader(handle))

    assert header == [
        "bank_txn_id",
        "value_date",
        "narration",
        "credit_paise",
        "debit_paise",
        "balance_paise",
    ]


# --- arithmetic honesty ---------------------------------------------------------


def test_settlement_net_is_exactly_the_fee_model_arithmetic() -> None:
    """Generator and Tier 1 must share one fee model. If the generator rounds even
    slightly differently, Tier 1 appears to work for the wrong reason."""
    profile = ChaosProfile(flags=frozenset({ChaosFlag.FEES}), intensity=0.0)
    for row in _batch(profile).settlements:
        if row.status != "captured":
            continue
        expected = DEFAULT_FEE_MODEL.breakdown(row.gross_amount_paise, row.method)
        assert row.fee_paise == expected["fee_paise"]
        assert row.gst_on_fee_paise == expected["gst_on_fee_paise"]
        assert row.tds_paise == expected["tds_paise"]
        assert row.net_amount_paise == expected["net_paise"]


# --- truth integrity ------------------------------------------------------------


def test_every_bank_credit_appears_in_ground_truth() -> None:
    """An unaccounted credit would be scored as a false negative that no matcher
    could ever have resolved, quietly depressing recall forever."""
    batch = _batch(ADVERSARIAL)
    credited = {row.bank_txn_id for row in batch.bank_txns if row.credit_paise > 0}
    linked = {link.bank_txn_id for link in batch.links}

    assert credited - linked == set()


def test_truth_link_identifiers_resolve_to_real_rows() -> None:
    batch = _batch(ADVERSARIAL)
    settlement_ids = {row.settlement_id for row in batch.settlements}
    invoice_ids = {row.invoice_id for row in batch.invoices}
    bank_ids = {row.bank_txn_id for row in batch.bank_txns}

    for link in batch.links:
        assert link.bank_txn_id in bank_ids
        if link.settlement_id is not None:
            assert link.settlement_id in settlement_ids
        if link.invoice_id is not None:
            assert link.invoice_id in invoice_ids


def test_orphan_credits_carry_no_settlement_link() -> None:
    """§5.5 ORPHAN_CREDIT: an out-of-band transfer has no gateway counterpart at all."""
    batch = _batch(ADVERSARIAL)
    orphans = [link for link in batch.links if link.link_type is LinkType.ORPHAN_CREDIT]

    assert orphans, "adversarial fixture planted no orphan credits"
    for link in orphans:
        assert link.settlement_id is None
        assert link.invoice_id is None


def test_refund_rate_stays_plausible_even_at_maximum_chaos() -> None:
    """Refund and dispute rates must not scale with `ChaosProfile.intensity`.

    Intensity governs how badly the *observability* of a batch is degraded. It has no
    business governing how often money fails to arrive. A statement where a large share
    of payments never landed stops looking like a bank statement, and a reviewer who
    works in finance will notice that long before checking any metric computed from it.
    """
    batch = generate_batch(settlements=250, seed=42, profile=ADVERSARIAL)
    never_settled = [row for row in batch.settlements if row.status in {"refunded", "disputed"}]

    assert len(never_settled) / len(batch.settlements) < 0.10


def test_link_type_records_cardinality_and_never_the_event() -> None:
    """A refunded settlement inside a batch is still a batch member.

    If the refund overwrote the link type, `eval/` would lose batch attribution for
    exactly those rows on day 8 — and it would look like the batching injector had
    simply fired less often.
    """
    batch = generate_batch(settlements=250, seed=42, profile=ADVERSARIAL)
    refunded = [link for link in batch.links if ChaosFlag.PARTIAL_REFUND in link.chaos_tags]

    assert refunded, "no partial refunds reached a bank credit"
    assert all(
        link.link_type in {LinkType.ONE_TO_ONE, LinkType.BATCH_MEMBER} for link in refunded
    )


def test_bank_transaction_ids_are_unique() -> None:
    """`schema.sql` declares PRIMARY KEY (run_id, bank_txn_id).

    A repeated id is not a duplicate for the matcher to detect — it is an
    `IntegrityError` that kills the ingest before any detection can happen.
    """
    batch = _batch(ADVERSARIAL)
    identifiers = [row.bank_txn_id for row in batch.bank_txns]

    assert len(identifiers) == len(set(identifiers))


def test_duplicate_post_reposts_the_same_money_under_a_new_identity() -> None:
    """§5.5 DUPLICATE_POST, read together with `ingest/loader.py`'s TODO.

    A re-post must be a *different row* carrying the *same money*. Byte-identical
    would be absorbed by the row fingerprint silently — precisely the double-counting
    the loader is required to surface as DUPLICATE_SUSPECTED.
    """
    batch = _batch(ADVERSARIAL)
    by_id = {row.bank_txn_id: row for row in batch.bank_txns}

    reposts = [
        link
        for link in batch.links
        if ChaosFlag.DUPLICATE_POST in link.chaos_tags and link.settlement_id is None
    ]
    assert len(reposts) == 1, "expected exactly one re-posted credit"
    repost = by_id[reposts[0].bank_txn_id]

    twins = [
        row
        for row in batch.bank_txns
        if row.bank_txn_id != repost.bank_txn_id
        and (row.credit_paise, row.value_date, row.narration)
        == (repost.credit_paise, repost.value_date, repost.narration)
    ]

    assert len(twins) == 1, "the re-post does not mirror exactly one original credit"
    assert twins[0].bank_txn_id != repost.bank_txn_id


def test_batched_payout_covers_several_settlements() -> None:
    """§5.5 BATCH. This is the cardinality problem Tier 2 exists for."""
    batch = _batch(REALISTIC)
    per_credit: dict[str, int] = {}
    for link in batch.links:
        if link.link_type is LinkType.BATCH_MEMBER:
            per_credit[link.bank_txn_id] = per_credit.get(link.bank_txn_id, 0) + 1

    assert per_credit, "no batched credits generated"
    assert max(per_credit.values()) >= 2


def test_ground_truth_never_leaks_into_the_three_input_files(tmp_path: Path) -> None:
    """The matcher reads these three files. If a truth column rode along inside one,
    the directory boundary in tests/test_no_truth_leak.py would be decorative."""
    paths = write_batch(_batch(ADVERSARIAL), tmp_path)
    truth_columns = {"link_type", "chaos_tags", "settlement_id_truth"}

    for key in ("invoices", "settlements", "bank_statement"):
        with paths[key].open(newline="") as handle:
            header = set(next(csv.reader(handle)))
        assert header & truth_columns == set(), f"{key} carries a truth column"


# --- the demo-critical property -------------------------------------------------


def test_adversarial_fixture_plants_a_genuinely_ambiguous_subset() -> None:
    """§5.5 DECOY_SUBSET, and the reason ADR-003 exists.

    Not enough for the generator to *claim* it planted a decoy — the second subset
    must actually sum to the same credit, or Tier 2 will match confidently and the
    centrepiece of the demo silently disappears.
    """
    batch = generate_batch(settlements=14, seed=42, profile=ADVERSARIAL)
    decoys = [link for link in batch.links if ChaosFlag.DECOY_SUBSET in link.chaos_tags]
    assert decoys, "adversarial fixture planted no decoy subsets"

    credits = {row.bank_txn_id: row for row in batch.bank_txns}
    target_txn = credits[decoys[0].bank_txn_id]

    # Deliberately a small batch: the whole settlement list stays brute-forceable, so
    # this test can never skip. A skipped test on the demo's centrepiece proves nothing.
    pool = batch.settlements
    assert len(pool) <= 16, f"pool of {len(pool)} is no longer brute-forceable"

    solutions = [
        combo
        for size in range(1, len(pool) + 1)
        for combo in itertools.combinations(pool, size)
        if sum(row.net_amount_paise for row in combo) == target_txn.credit_paise
    ]

    assert len(solutions) >= 2, (
        f"decoy credit {target_txn.bank_txn_id} has {len(solutions)} valid explanation(s); "
        "AMBIGUOUS_SUBSET can never fire"
    )


# --- fixtures on disk -----------------------------------------------------------


def test_generate_fixture_writes_all_four_files(tmp_path: Path) -> None:
    paths = generate_fixture(
        fixture="realistic", settlements=SETTLEMENT_COUNT, seed=42, out_dir=tmp_path
    )

    assert set(paths) == EXPECTED_OUTPUT_KEYS
    for path in paths.values():
        assert path.exists() and path.stat().st_size > 0


def test_unknown_fixture_name_is_rejected(tmp_path: Path) -> None:
    """A typo must not silently fall back to a different corruption level."""
    with pytest.raises(KeyError):
        generate_fixture(fixture="realsitic", settlements=60, seed=42, out_dir=tmp_path)


def test_fixtures_increase_in_difficulty() -> None:
    """easy ⊂ realistic ⊂ adversarial. The ablation story depends on this ordering."""
    assert EASY.flags < REALISTIC.flags < ADVERSARIAL.flags
