"""The HTML report — §12's buffer-policy deliverable, and the demo surface.

§12 cut the FastAPI + React UI and named the fallback: *a static HTML report generated by
the CLI*. This is that report. One self-contained file, no server, no build step, no
network — a judge opens it on a laptop with no key and no internet.

Two properties carry the weight here, and both are easy to lose silently:

**Self-containment.** A CDN reference that resolves on a developer's machine and fails on
a plane is the worst kind of bug: invisible until the moment it is being demonstrated. So
the page must contain no outward reference of any kind — no script src, no stylesheet
link, no remote font, no image URL.

**Nothing is computed in the template.** Every figure is passed in, already scored. A
renderer that derives a percentage is a renderer that can disagree with
`results/metrics.md`, and rule 7 exists precisely because two sources for one number is
how a wrong number ships.

The renderer is also deliberately *pure* — data in, string out, no database, no filesystem,
no ground truth. That is what lets it live in `ledgerloop/` at all: `eval/` computes
precision, because `eval/` is the only package permitted to read truth, and hands the
result over. `tests/test_no_truth_leak.py` stays untouched.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from eval.metrics import RunMetrics
from ledgerloop.exceptions.codes import ExceptionCode
from ledgerloop.report.html import render_report
from ledgerloop.report.model import (
    Adjudication,
    GateStage,
    ProvenanceRow,
    ReportData,
    RunHeader,
    TierStep,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
COMMITTED_CACHE = REPO_ROOT / "fixtures" / "llm_cache"


# --- fixtures ----------------------------------------------------------------------


def _metrics(**over: object) -> RunMetrics:
    base = dict(
        credits_total=165, credits_explainable=156, matches_posted=112,
        matches_correct=112, matches_incorrect=0, auto_match_rate=0.679,
        precision=1.0, recall=0.718, false_match_rate=0.0,
        exceptions_by_code={"POOL_TOO_LARGE": 54}, llm_invocations=0, cache_hits=61,
        value_reconciled_paise=342569696, value_at_risk_paise=332384787, seconds=1.5,
    )
    base.update(over)
    return RunMetrics(**base)  # type: ignore[arg-type]


def _data(**over: object) -> ReportData:
    base = dict(
        run=RunHeader(run_id="demo", fixture="adversarial", records=250, seed=42,
                      tiers="0,1,2,3", rows_ingested=665, rows_quarantined=0,
                      keyless=True),
        metrics=_metrics(),
        tiers=[TierStep(tier=0, credits=22, settlements=22),
               TierStep(tier=1, credits=21, settlements=21),
               TierStep(tier=2, credits=55, settlements=84),
               TierStep(tier=3, credits=14, settlements=15)],
        residual=53,
        clusters=[],
        provenance=[],
        adjudications=[],
        ablation_rows=[],
    )
    base.update(over)
    return ReportData(**base)  # type: ignore[arg-type]


# --- self-containment ---------------------------------------------------------------


def test_the_page_makes_no_outward_request() -> None:
    """The failure this test exists to prevent is invisible until the demo.

    A CDN font or script resolves fine on the machine that built it and fails on a plane,
    on a locked-down network, or in a judging room with bad wifi.

    Checks for constructs that *fetch* — not for the characters "https://". A URL can
    legitimately appear as text: Pydantic's validation errors carry one, and that message
    is displayed verbatim as the schema gate's reason. Asserting the substring would
    pressure someone into stripping a real diagnostic to satisfy a test that was measuring
    the wrong thing.
    """
    html = render_report(_data())

    assert not re.search(r"<link[^>]", html)
    assert not re.search(r"<script[^>]*\ssrc\s*=", html)
    assert not re.search(r"<img[^>]*\ssrc\s*=", html)
    assert "@import" not in html
    assert not re.search(r"url\(\s*['\"]?https?:", html)


def test_a_url_inside_displayed_text_does_not_count_as_a_request() -> None:
    """Encodes the distinction the test above rests on, so nobody re-tightens it.

    Pydantic appends a documentation link to its validation errors, and that text is shown
    as the reason the schema gate rejected a response. It is content. The page fetches
    nothing.
    """
    html = render_report(_data(adjudications=[Adjudication(
        bank_txn_id="BNK1", credit_paise=100, value_date="2026-08-01", narration="n",
        candidates=[], candidates_total=1, prompt="p", raw_response="r",
        stages=[GateStage(gate="schema", passed=False,
                          detail="see https://errors.pydantic.dev/2.13/v/string_too_long")],
        verdict="LLM_INVALID_OUTPUT", scripted=False)]))

    assert "errors.pydantic.dev" in html
    assert not re.search(r"<link[^>]", html)
    assert not re.search(r"<script[^>]*\ssrc\s*=", html)


def test_the_page_is_one_file_with_no_placeholder_left_behind() -> None:
    html = render_report(_data())

    # Not a naive brace check: CSS media queries legitimately end in "}}". Look for the
    # substitution sentinels this module actually uses.
    assert "__BLURB__" not in html and "__GW__" not in html
    assert html.lstrip().startswith("<!doctype html>")
    assert html.rstrip().endswith("</html>")


# --- nothing is computed in the template --------------------------------------------


def test_every_headline_figure_comes_from_the_passed_metrics() -> None:
    """Rule 7, applied to the renderer. If the template derived a rate it could disagree
    with `results/metrics.md`, and two sources for one number is how a wrong number
    ships."""
    html = render_report(_data(metrics=_metrics(
        auto_match_rate=0.123, precision=0.456, false_match_rate=0.789)))

    assert "12.3%" in html
    assert "45.6%" in html
    assert "78.9%" in html


def test_a_run_with_no_metrics_still_renders() -> None:
    """`reconcile` can run without truth available. The page must degrade to the parts it
    can show rather than failing to generate at all."""
    html = render_report(_data(metrics=None))

    assert "demo" in html
    assert "not scored" in html.lower()


# --- empty states -------------------------------------------------------------------


@pytest.mark.parametrize(
    "field", ["clusters", "provenance", "adjudications", "ablation_rows"]
)
def test_each_section_survives_being_empty(field: str) -> None:
    """Report generators break on empty states, and a perfectly reconciled batch is the
    one case a finance team most wants to see rendered."""
    html = render_report(_data(**{field: []}))

    assert html.rstrip().endswith("</html>")


def test_a_run_that_matched_nothing_renders() -> None:
    html = render_report(_data(
        tiers=[TierStep(tier=0, credits=0, settlements=0)], residual=165,
        metrics=_metrics(matches_posted=0, matches_correct=0, auto_match_rate=0.0)))

    assert "0.0%" in html


# --- escaping -----------------------------------------------------------------------


def test_values_from_the_bank_file_are_escaped() -> None:
    """Narration is free text arriving from a third party. It lands in the DOM, so it is
    escaped — not because a bank statement is hostile, but because a renderer that trusts
    its input is one CSV away from a broken page."""
    nasty = '<script>alert("x")</script>'
    html = render_report(_data(provenance=[ProvenanceRow(
        bank_txn_id=nasty, settlement_ids=("STL1",), tier=0, rule_id="T0",
        confidence=1.0, evidence=[], fingerprints=("abc",),
        model_name=None, prompt_version=None)]))

    assert "<script>alert" not in html
    assert "&lt;script&gt;" in html


# --- provenance ---------------------------------------------------------------------


def test_tier_three_rows_show_the_model_and_prompt_version() -> None:
    """The panel that made ADR-037's defect visible. A Tier 3 match with no model in the
    trail is a match nobody can audit."""
    html = render_report(_data(provenance=[ProvenanceRow(
        bank_txn_id="BNK1", settlement_ids=("STL1",), tier=3, rule_id="T3-ADJUDICATED",
        confidence=0.99, evidence=[], fingerprints=("abc123",),
        model_name="gemini-3.5-flash-lite", prompt_version="v1")]))

    assert "gemini-3.5-flash-lite" in html
    assert "v1" in html


def test_lower_tier_rows_say_arithmetic_decided_rather_than_naming_a_model() -> None:
    """Rule 1 made visible: tiers 0-2 never call a model, and the trail should say so
    rather than leaving a blank a reader has to interpret."""
    html = render_report(_data(provenance=[ProvenanceRow(
        bank_txn_id="BNK1", settlement_ids=("STL1",), tier=0, rule_id="T0-UTR-EXACT",
        confidence=1.0, evidence=[], fingerprints=("abc",),
        model_name=None, prompt_version=None)]))

    assert "arithmetic decided" in html


# --- the adjudication replay --------------------------------------------------------


def test_an_adjudication_shows_prompt_response_and_every_gate() -> None:
    """The demo surface. Showing the verdict without the prompt and the raw response
    would be asking the viewer to take the gates on trust, which is the opposite of the
    point."""
    html = render_report(_data(adjudications=[Adjudication(
        bank_txn_id="BNK00128", credit_paise=5313950, value_date="2026-08-28",
        narration="NEFT-CR/HDFC/Sunrise Packaging", candidates=[],
        candidates_total=8, prompt="PROMPT-TEXT-HERE", raw_response="RAW-RESPONSE-HERE",
        stages=[GateStage(gate="schema", passed=True, detail=""),
                GateStage(gate="membership", passed=True, detail=""),
                GateStage(gate="arithmetic", passed=False,
                          detail="proposed settlements sum to 5719836 against 5313950")],
        verdict=ExceptionCode.AMOUNT_BEYOND_TOLERANCE.value, scripted=False)]))

    assert "PROMPT-TEXT-HERE" in html
    assert "RAW-RESPONSE-HERE" in html
    assert "5719836" in html
    for gate in ("schema", "membership", "arithmetic"):
        assert gate in html.lower()


def test_a_scripted_adjudication_is_labelled_as_scripted() -> None:
    """§7.3 requires demonstrating that a fabricated identifier discards the whole
    response, and no measured run ever produced one — zero hallucinated ids across every
    arm. So that case is scripted, and the page must say so rather than implying a real
    model did it."""
    html = render_report(_data(adjudications=[Adjudication(
        bank_txn_id="BNK1", credit_paise=100, value_date="2026-08-01", narration="n",
        candidates=[], candidates_total=1, prompt="p", raw_response="r",
        stages=[GateStage(gate="schema", passed=True, detail="")],
        verdict="LLM_INVALID_OUTPUT", scripted=True)]))

    assert "scripted" in html.lower()


# --- the replay itself --------------------------------------------------------------


def test_replay_reads_the_committed_cache_and_calls_nothing(tmp_path: Path) -> None:
    """Replays are built from cached responses, so the demo cannot rate-limit, time out,
    or answer differently on stage. Both of those failures happened during the real
    sweeps (ADR-031)."""
    from ledgerloop.report.replay import replay_tier3

    cases = replay_tier3(
        fixture="adversarial", records=250, seed=42,
        cache_dir=COMMITTED_CACHE, workdir=tmp_path, limit=4,
    )

    assert cases, "no cached adjudications found — has the cache moved?"
    for case in cases:
        assert case.prompt and case.raw_response
        assert case.stages


def test_replay_finds_a_rejection_not_only_successes(tmp_path: Path) -> None:
    """A demo showing only clean matches proves nothing about the gates. The rejections
    are the evidence."""
    from ledgerloop.report.replay import replay_tier3

    cases = replay_tier3(
        fixture="adversarial", records=250, seed=42,
        cache_dir=COMMITTED_CACHE, workdir=tmp_path, limit=6,
    )
    verdicts = {c.verdict for c in cases}

    assert len(verdicts) > 1, f"every replayed case ended the same way: {verdicts}"
    assert any(not s.passed for c in cases for s in c.stages)


def test_replay_is_deterministic(tmp_path: Path) -> None:
    """§7.4. Two replays of one fixture must produce the same cases in the same order, or
    the demo is not reproducible and neither is the page."""
    from ledgerloop.report.replay import replay_tier3

    kw = dict(fixture="adversarial", records=250, seed=42, cache_dir=COMMITTED_CACHE, limit=3)
    first = replay_tier3(workdir=tmp_path / "a", **kw)  # type: ignore[arg-type]
    second = replay_tier3(workdir=tmp_path / "b", **kw)  # type: ignore[arg-type]

    assert [c.bank_txn_id for c in first] == [c.bank_txn_id for c in second]
    assert [c.verdict for c in first] == [c.verdict for c in second]


def test_replay_never_reaches_ground_truth() -> None:
    """`ledgerloop/` may not read truth_links.csv. The replay lives there, so it must be
    buildable from the run and the cache alone.

    Checks for the tokens a leak would actually introduce rather than the word "truth" —
    the module's own docstring says it does not read ground truth, and a test that cannot
    tell an explanation from a violation is a test that will be silenced rather than
    fixed. `tests/test_no_truth_leak.py` remains the authoritative guard for the package
    as a whole; this is a local assertion about the newest module in it.
    """
    source = (REPO_ROOT / "ledgerloop" / "report" / "replay.py").read_text(encoding="utf-8")

    assert "truth_links" not in source
    assert "from eval" not in source
    assert "import eval" not in source
