"""Render the run report as one self-contained HTML file.

§12 cut the FastAPI + React UI and named the fallback outright: *a static HTML report
generated by the CLI*. This is it.

**A pure function: data in, string out.** No database, no filesystem, no ground truth. The
page shows precision and false-match rate, and computing those needs truth, which
`ledgerloop/` may never read (rule 6) — so `eval/` scores the run and hands the numbers
over. Nothing here derives a figure; a renderer that computed a percentage could disagree
with `results/metrics.md`, and two sources for one number is how a wrong number ships.

**No outward references.** No CDN, no webfont, no remote script. A font that resolves on
the machine that built the page and fails on a plane is the worst kind of bug: invisible
until the moment it is being demonstrated. The type is a system stack, and the design
carries itself on palette, spacing and the monospaced data columns instead.
"""

from __future__ import annotations

import html as _html
import json
from typing import Any

from ledgerloop.report.model import ProvenanceRow, ReportData

TIER_TOKENS = ("--t0", "--t1", "--t2", "--t3")

TIER_CAPTION = {
    0: ("Tier 0 · exact", "reference or amount+date, unique on both sides"),
    1: ("Tier 1 · tolerant", "fee model recomputed, window and fuzzy reference"),
    2: ("Tier 2 · subset-sum", "batched payouts, declined when two subsets fit"),
    3: ("Tier 3 · adjudicated", "model proposes, Python verifies, numbers win"),
}

VERDICT_BLURB = {
    "POSTED": "All checks held. The match is posted with full provenance.",
    "AMOUNT_BEYOND_TOLERANCE": (
        "The model asserted a total that does not add up. Python recomputed it and refused."
    ),
    "LLM_INVALID_OUTPUT": (
        "The response never became a proposal. Nothing was posted, and there is no retry."
    ),
    "LOW_CONFIDENCE": "The model was not confident enough to act on. Sent to a human.",
}

GATE_QUESTION = {
    "schema": "Does it satisfy the output contract?",
    "membership": "Is every id from the candidate set it was given?",
    "arithmetic": "Do the numbers reconcile, recomputed in Python?",
    "confidence": "Is it confident enough to act on?",
}


def e(value: object) -> str:
    """Escape anything bound for the DOM.

    Narration is free text from a third party. It is escaped not because a bank statement
    is hostile, but because a renderer that trusts its input is one unusual CSV away from
    a broken page.
    """
    return _html.escape(str(value), quote=True)


def rupees(paise: int) -> str:
    """Integer paise to rupees, grouped the Indian way.

    Integer arithmetic throughout — no float ever touches a money value, including on the
    way to being displayed. The grouping is lakh/crore because that is how the domain
    writes amounts, and a report that formats them like a US ledger reads as foreign to
    the people who would use it.
    """
    sign = "-" if paise < 0 else ""
    whole, part = divmod(abs(paise), 100)
    digits = str(whole)
    if len(digits) > 3:
        head, tail = digits[:-3], digits[-3:]
        groups = []
        while len(head) > 2:
            groups.insert(0, head[-2:])
            head = head[:-2]
        if head:
            groups.insert(0, head)
        digits = ",".join([*groups, tail])
    return f"{sign}₹{digits}.{part:02d}"


def pct(value: float) -> str:
    return f"{value * 100:.1f}%"


def _stat(label: str, value: str, note: str, *, hero: bool = False) -> str:
    return (
        f'<div class="stat{" hero" if hero else ""}"><div class="stat-k">{e(label)}</div>'
        f'<div class="stat-v">{e(value)}</div><div class="stat-n">{e(note)}</div></div>'
    )


def _cascade(data: ReportData) -> str:
    segments = []
    legend = []
    for i, step in enumerate(data.tiers):
        name, why = TIER_CAPTION.get(step.tier, (f"Tier {step.tier}", ""))
        token = TIER_TOKENS[min(step.tier, 3)]
        segments.append(
            f'<div class="seg" style="flex:{step.credits};background:var({token});'
            f'animation-delay:{i * 70}ms" title="{e(name)} — {step.credits} credits">'
            f"{step.credits}</div>"
        )
        legend.append(
            f'<div><span class="swatch" style="background:var({token})"></span>'
            f"<div><b>{e(name)}</b> · <span>{e(why)}</span></div></div>"
        )
    if data.residual:
        segments.append(
            f'<div class="seg residual" style="flex:{data.residual}" '
            f'title="Exception queue — {data.residual} credits">{data.residual}</div>'
        )
        legend.append(
            '<div><span class="swatch" style="background:var(--border-firm)"></span>'
            "<div><b>Exception queue</b> · <span>reason-coded, never guessed</span></div></div>"
        )
    return (
        '<div class="cascade"><div class="bar">' + "".join(segments) + "</div>"
        '<div class="legend">' + "".join(legend) + "</div></div>"
    )


def _ablation(data: ReportData) -> str:
    if not data.ablation_rows:
        return ""
    rows = []
    for row in data.ablation_rows:
        if not row.measured:
            rows.append(
                f"<tr><td>{e(row.label)}</td>"
                f'<td class="r" colspan="5"><em>not yet measured</em></td></tr>'
            )
            continue
        cls = ""
        if row.label == "Full cascade":
            cls = ' class="win"'
        elif row.label.startswith("LLM-only"):
            cls = ' class="lose"'
        fm = f'<span class="{"bad" if row.false_match_rate else "zero"}">' \
             f"{pct(row.false_match_rate)}</span>"
        wrong = f'<span class="bad">{row.matches_incorrect}</span>' \
            if row.matches_incorrect else "0"
        rows.append(
            f"<tr{cls}><td>{e(row.label)}</td>"
            f'<td class="r num">{pct(row.auto_match_rate)}</td>'
            f'<td class="r num">{pct(row.precision)}</td>'
            f'<td class="r num">{fm}</td>'
            f'<td class="r num">{row.adjudications}</td>'
            f'<td class="r num">{wrong}</td></tr>'
        )
    return (
        "<section><h2>Ablation — §9.2</h2>"
        '<p class="lede">The same fixture, the same model, the same gates in both model '
        "arms. The cascade wins because the deterministic tiers mean the model is asked "
        "fewer questions — not because its gates are better.</p>"
        '<div class="scroll"><table><thead><tr><th>Configuration</th>'
        '<th class="r">Auto-match</th><th class="r">Precision</th>'
        '<th class="r">False-match</th><th class="r">Adjudications</th>'
        '<th class="r">Wrong</th></tr></thead><tbody>' + "".join(rows) + "</tbody></table></div>"
        "</section>"
    )


def _clusters(data: ReportData) -> str:
    if not data.clusters:
        return (
            "<section><h2>Exception queue</h2>"
            '<p class="lede">Nothing open. Every credit was either explained or is an '
            "orphan no matcher should resolve.</p></section>"
        )
    total = sum(c.value_at_risk_paise for c in data.clusters)
    count = sum(c.count for c in data.clusters)
    widest = max(c.value_at_risk_paise for c in data.clusters) or 1
    cards = []
    for cl in data.clusters:
        severity = "var(--crit)" if cl.count >= 15 else (
            "var(--warn)" if cl.count >= 5 else "var(--muted)"
        )
        cards.append(
            f'<div class="cl" style="--sev:{severity}"><div class="cl-top">'
            f'<span class="code">{e(cl.code)}</span>'
            f'<span class="count">&times;{cl.count}</span>'
            f'<span class="risk">{rupees(cl.value_at_risk_paise)}</span></div>'
            f'<p class="cl-why">{e(cl.diagnosis)}</p>'
            f'<div class="meter"><i style="width:'
            f'{cl.value_at_risk_paise / widest * 100:.1f}%"></i></div></div>'
        )
    return (
        f"<section><h2>Exception queue — {count} open, {rupees(total)} at risk</h2>"
        '<p class="lede">Clustered by reason code and sorted by rupees at risk. Records '
        "sharing a code are one wrong assumption, not many problems.</p>"
        '<div class="clusters">' + "".join(cards) + "</div></section>"
    )


def _provenance_row(row: ProvenanceRow) -> str:
    evidence = "".join(
        f'<div class="ev"><div class="ev-f">{e(item.field_name)}</div>'
        f'<div class="ev-cmp"><span>{e(item.bank_value)}</span>'
        f'<span class="arrow">↔</span><span>{e(item.settlement_value)}</span></div>'
        f'<div class="ev-n">{e(item.note)}</div></div>'
        for item in row.evidence
    )
    if row.model_name:
        model = f"<b>{e(row.model_name)} · {e(row.prompt_version)}</b>"
    else:
        model = '<b style="color:var(--muted)">none — arithmetic decided</b>'
    return (
        '<details class="prov"><summary>'
        f'<span class="tier" style="background:var({TIER_TOKENS[min(row.tier, 3)]})">'
        f"T{row.tier}</span>"
        f'<span><span class="txn">{e(row.bank_txn_id)}</span> '
        f'<span class="rule">→ {e(", ".join(row.settlement_ids))}</span></span>'
        f'<span class="conf">{row.confidence:.2f}</span>'
        '<span class="caret">▶</span></summary>'
        f'<div class="body">{evidence}'
        f'<div class="meta"><div>rule<b>{e(row.rule_id)}</b></div>'
        f"<div>model{model}</div>"
        '<div style="flex:1 1 260px">source fingerprints (sha-256)'
        f'<b class="hash">{"<br>".join(e(f[:16]) for f in row.fingerprints)}</b></div>'
        "</div></div></details>"
    )


def _provenance(data: ReportData) -> str:
    if not data.provenance:
        return ""
    return (
        "<section><h2>Provenance</h2>"
        '<p class="lede">Every posted match carries the tier that decided it, the rule, '
        "the evidence, and the SHA-256 of every source row that fed the decision. Tier 3 "
        "additionally carries the model and prompt version, so a prompt change is visible "
        "in the trail rather than inferred.</p>"
        '<div class="filters" id="filters"></div>'
        '<div class="scroll" id="prov">'
        + "".join(_provenance_row(r) for r in data.provenance)
        + "</div></section>"
    )


def _adjudications(data: ReportData) -> str:
    if not data.adjudications:
        return ""
    return (
        "<section><h2>Adjudication — watch a credit go through Tier 3</h2>"
        '<p class="lede">Each case shows the candidate pool the model was given, the exact '
        "prompt it received, the raw text it returned, and the gates running on that text "
        "in order. Every response was replayed from the committed cache — no network, no "
        "key, identical on every machine.</p>"
        '<div class="theatre"><div class="picker" id="picker" role="tablist"></div>'
        '<div class="stage-grid">'
        '<div class="pane"><div class="pane-h"><span class="step-n">1</span>'
        "The credit, and the pool it was given</div><div id=\"credit\"></div>"
        '<div class="pane-h" style="margin-top:20px"><span class="step-n">2</span>'
        'Prompt sent</div><pre id="prompt"></pre></div>'
        '<div class="pane"><div class="pane-h"><span class="step-n">3</span>'
        'What the model returned</div><pre id="raw"></pre>'
        '<div class="pane-h" style="margin-top:20px"><span class="step-n">4</span>'
        'Gates, in order, short-circuiting</div><div class="gates" id="gates"></div>'
        '<div id="verdict"></div></div></div>'
        '<div class="runbar"><button class="run" id="run">Run the gates</button>'
        '<span class="runnote">replayed from cache · 0 API calls · 0 rupees</span>'
        "</div></div></section>"
    )


def _payload(data: ReportData) -> str:
    """Serialise the adjudications for the client-side step-through.

    Embedded rather than fetched, because the page must work from a file:// URL with no
    server and no network.
    """
    cases: list[dict[str, Any]] = []
    for case in data.adjudications:
        cases.append(
            {
                "txn": case.bank_txn_id,
                "credit": case.credit_paise,
                "date": case.value_date,
                "narration": case.narration,
                "n": case.candidates_total,
                "cands": [
                    {"id": c.settlement_id, "cust": c.customer_name, "gross": c.gross_amount_paise}
                    for c in case.candidates
                ],
                "prompt": case.prompt,
                "raw": case.raw_response,
                "stages": [
                    {"gate": s.gate, "ok": s.passed, "why": s.detail} for s in case.stages
                ],
                "verdict": case.verdict,
                "scripted": case.scripted,
            }
        )
    # </script> inside embedded data would close the tag early.
    return json.dumps(cases, separators=(",", ":")).replace("</", "<\\/")


def render_report(data: ReportData) -> str:
    """Render the whole page. Pure: no I/O, no truth, nothing computed."""
    m = data.metrics
    run = data.run

    if m is not None:
        stats = (
            _stat("Auto-match", pct(m.auto_match_rate),
                  f"{m.matches_posted} of {m.credits_total} credits posted")
            + _stat("Precision", pct(m.precision),
                    f"{m.matches_incorrect} of {m.matches_posted} posted wrongly")
            + _stat("False-match rate", pct(m.false_match_rate),
                    "the number this system optimises", hero=True)
            + _stat("Value reconciled", rupees(m.value_reconciled_paise),
                    f"{rupees(m.value_at_risk_paise)} still at risk")
        )
        adjudicated = sum(s.credits for s in data.tiers if s.tier == 3)
        thesis = (
            f"An LLM touched <em>{adjudicated} of {m.credits_total}</em> credits, "
            "and decided none of them."
        )
    else:
        stats = _stat("Accuracy", "not scored",
                      "ground truth was not available for this run")
        thesis = "Reconciled without a model having the final say."

    keyless = (
        '<span class="keyless">no API key</span>' if run.keyless else ""
    )

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>LedgerLoop — run {e(run.run_id)}</title>
<style>{_CSS}</style>
</head>
<body>
<div class="strip"><div class="strip-in">
  <div class="mark">Ledger<span>Loop</span></div>
  <div class="facts">
    <div>run <b>{e(run.run_id)}</b></div>
    <div>fixture <b>{e(run.fixture)}</b></div>
    <div>records <b>{run.records}</b></div>
    <div>seed <b>{run.seed}</b></div>
    <div>tiers <b>{e(run.tiers)}</b></div>
    <div>ingested <b>{run.rows_ingested}</b> · quarantined <b>{run.rows_quarantined}</b></div>
  </div>
  {keyless}
</div></div>
<div class="wrap">
  <p class="thesis">{thesis}</p>
  <p class="thesis-sub">Every proposal the model made was re-verified in Python against the
  fee model and the settlement window before a rupee moved.</p>
  <div class="stats">{stats}</div>
  <section><h2>The cascade</h2>
    <p class="lede">Each tier only sees what the tier above it could not resolve.
    Arithmetic runs first and settles the majority; the model is asked about what is
    left.</p>
    {_cascade(data)}
  </section>
  {_adjudications(data)}
  {_ablation(data)}
  {_clusters(data)}
  {_provenance(data)}
  <p class="foot">Generated by <code>ledgerloop report --html</code> from run
  <code>{e(run.run_id)}</code>. Every figure was scored against the generator's ground
  truth; none was typed by hand.</p>
</div>
<script>const CASES={_payload(data)};{_JS}</script>
</body>
</html>
"""


_CSS = """
:root{--ground:#F4F6F8;--surface:#FFF;--raised:#FAFBFC;--border:#DCE3E9;--border-firm:#C4CFD8;
--ink:#111A22;--ink-soft:#3B4A57;--muted:#64757F;--brass:#96702A;--brass-soft:#F0E4CC;
--ok:#2E7D55;--warn:#A8632A;--crit:#A63F39;--t0:#3E6E96;--t1:#3F8177;--t2:#8A7F35;--t3:#96702A;
--shadow:0 1px 2px rgba(17,26,34,.06),0 8px 24px -12px rgba(17,26,34,.14);
--mono:ui-monospace,"SF Mono","Cascadia Mono","Roboto Mono",Menlo,Consolas,monospace;
--sans:system-ui,-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
--serif:ui-serif,Georgia,"Times New Roman",serif}
@media (prefers-color-scheme:dark){:root:not([data-theme="light"]){
--ground:#0E141A;--surface:#151D25;--raised:#1B242D;--border:#25323D;--border-firm:#33434F;
--ink:#E6EBF0;--ink-soft:#B4C1CC;--muted:#8697A6;--brass:#D5A748;--brass-soft:#2A2415;
--ok:#4BA97A;--warn:#D98A45;--crit:#D96B63;--t0:#5B8DB8;--t1:#5FA79C;--t2:#B0A55F;--t3:#D5A748;
--shadow:0 1px 2px rgba(0,0,0,.4),0 10px 30px -14px rgba(0,0,0,.7)}}
:root[data-theme="dark"]{--ground:#0E141A;--surface:#151D25;--raised:#1B242D;--border:#25323D;
--border-firm:#33434F;--ink:#E6EBF0;--ink-soft:#B4C1CC;--muted:#8697A6;--brass:#D5A748;
--brass-soft:#2A2415;--ok:#4BA97A;--warn:#D98A45;--crit:#D96B63;--t0:#5B8DB8;--t1:#5FA79C;
--t2:#B0A55F;--t3:#D5A748;--shadow:0 1px 2px rgba(0,0,0,.4),0 10px 30px -14px rgba(0,0,0,.7)}
*{box-sizing:border-box}html{color-scheme:light dark}
body{margin:0;background:var(--ground);color:var(--ink);font-family:var(--sans);font-size:15px;
line-height:1.55;-webkit-font-smoothing:antialiased}
.wrap{max-width:1180px;margin:0 auto;padding:0 28px 96px}
.num{font-family:var(--mono);font-variant-numeric:tabular-nums}
.strip{position:sticky;top:0;z-index:20;background:var(--surface);
border-bottom:1px solid var(--border);margin-bottom:40px}
.strip-in{max-width:1180px;margin:0 auto;padding:12px 28px;display:flex;align-items:center;
gap:22px;flex-wrap:wrap}
.mark{font-family:var(--serif);font-weight:600;font-size:17px}
.mark span{color:var(--brass)}
.facts{display:flex;gap:18px;flex-wrap:wrap;margin-left:auto;font-family:var(--mono);
font-size:11.5px;color:var(--muted)}
.facts b{color:var(--ink-soft);font-weight:500}
.keyless{display:inline-flex;align-items:center;gap:6px;padding:3px 9px;
border:1px solid var(--border-firm);border-radius:999px;font-family:var(--mono);
font-size:11px;color:var(--ok)}
.keyless::before{content:"";width:6px;height:6px;border-radius:50%;background:var(--ok)}
.thesis{font-family:var(--serif);font-size:clamp(21px,3vw,29px);line-height:1.35;max-width:24ch;
font-weight:400;text-wrap:balance;margin:0 0 8px}
.thesis em{font-style:italic;color:var(--brass)}
.thesis-sub{color:var(--muted);max-width:60ch;margin:0 0 36px;font-size:14.5px}
.stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:14px;
margin-bottom:44px}
.stat{background:var(--surface);border:1px solid var(--border);border-radius:10px;
padding:18px 20px 16px;box-shadow:var(--shadow);position:relative;overflow:hidden}
.stat.hero{border-color:var(--ok)}
.stat.hero::after{content:"";position:absolute;inset:0 auto 0 0;width:3px;background:var(--ok)}
.stat-k{font-family:var(--mono);font-size:10.5px;letter-spacing:.09em;text-transform:uppercase;
color:var(--muted);margin-bottom:10px}
.stat-v{font-family:var(--mono);font-variant-numeric:tabular-nums;font-size:31px;font-weight:600;
line-height:1;letter-spacing:-.02em}
.stat.hero .stat-v{color:var(--ok)}
.stat-n{font-size:12.5px;color:var(--muted);margin-top:8px}
section{margin-bottom:52px}
h2{font-size:12px;font-weight:600;letter-spacing:.1em;text-transform:uppercase;
color:var(--muted);margin:0 0 4px}
.lede{color:var(--ink-soft);font-size:14px;margin:0 0 20px;max-width:70ch}
.cascade{background:var(--surface);border:1px solid var(--border);border-radius:10px;
padding:24px;box-shadow:var(--shadow)}
.bar{display:flex;height:46px;border-radius:6px;overflow:hidden;margin-bottom:16px}
.seg{display:flex;align-items:center;justify-content:center;font-family:var(--mono);
font-size:12.5px;font-weight:600;color:#fff;transform-origin:left;
animation:grow .55s cubic-bezier(.2,.7,.3,1) backwards;transition:filter .15s}
.seg:hover{filter:brightness(1.12)}
@keyframes grow{from{transform:scaleX(0)}to{transform:scaleX(1)}}
.seg.residual{background:repeating-linear-gradient(45deg,var(--raised),var(--raised) 6px,
var(--border) 6px,var(--border) 12px);color:var(--muted)}
.legend{display:flex;gap:20px;flex-wrap:wrap;font-size:12.5px}
.legend>div{display:flex;align-items:baseline;gap:8px}
.swatch{width:9px;height:9px;border-radius:2px;flex:none;transform:translateY(-1px)}
.legend b{font-family:var(--mono);font-weight:600}
.legend span{color:var(--muted)}
.scroll{overflow-x:auto;border:1px solid var(--border);border-radius:10px;
background:var(--surface);box-shadow:var(--shadow)}
table{width:100%;border-collapse:collapse;font-size:13.5px}
th{font-family:var(--mono);font-size:10.5px;letter-spacing:.08em;text-transform:uppercase;
color:var(--muted);text-align:left;padding:12px 16px;font-weight:500;
border-bottom:1px solid var(--border);white-space:nowrap}
td{padding:11px 16px;border-bottom:1px solid var(--border);vertical-align:top}
tbody tr:last-child td{border-bottom:none}
.r{text-align:right}td.r,th.r{font-variant-numeric:tabular-nums}
tr.win td{background:color-mix(in srgb,var(--ok) 7%,transparent)}
tr.lose td{background:color-mix(in srgb,var(--crit) 6%,transparent)}
.zero{color:var(--ok);font-weight:600}.bad{color:var(--crit);font-weight:600}
.clusters{display:flex;flex-direction:column;gap:10px}
.cl{background:var(--surface);border:1px solid var(--border);border-left:3px solid var(--sev);
border-radius:8px;padding:14px 18px;box-shadow:var(--shadow)}
.cl-top{display:flex;align-items:baseline;gap:12px;flex-wrap:wrap;margin-bottom:6px}
.code{font-family:var(--mono);font-size:12.5px;font-weight:600;color:var(--sev)}
.count{font-family:var(--mono);font-size:11.5px;color:var(--muted)}
.risk{margin-left:auto;font-family:var(--mono);font-variant-numeric:tabular-nums;
font-size:14px;font-weight:600}
.cl-why{font-size:13px;color:var(--ink-soft);margin:0}
.meter{height:3px;border-radius:2px;background:var(--border);margin-top:10px;overflow:hidden}
.meter i{display:block;height:100%;background:var(--sev)}
.filters{display:flex;gap:6px;margin-bottom:14px;flex-wrap:wrap}
.chip{font-family:var(--mono);font-size:11.5px;padding:5px 12px;border-radius:999px;
border:1px solid var(--border-firm);background:var(--surface);color:var(--ink-soft);
cursor:pointer}
.chip:hover{border-color:var(--brass)}
.chip[aria-pressed="true"]{background:var(--ink);color:var(--ground);border-color:var(--ink)}
.chip:focus-visible,summary:focus-visible,.run:focus-visible,.pick:focus-visible{
outline:2px solid var(--brass);outline-offset:2px}
.tier{font-family:var(--mono);font-size:11px;font-weight:600;padding:2px 7px;border-radius:4px;
color:#fff;white-space:nowrap}
details.prov{border-bottom:1px solid var(--border)}
details.prov:last-child{border-bottom:none}
summary{list-style:none;cursor:pointer;padding:12px 16px;display:grid;
grid-template-columns:66px 1fr auto auto;gap:14px;align-items:center}
summary::-webkit-details-marker{display:none}
summary:hover{background:var(--raised)}
.txn{font-family:var(--mono);font-size:13px;font-weight:500}
.rule{font-family:var(--mono);font-size:11.5px;color:var(--muted)}
.conf{font-family:var(--mono);font-size:12.5px;font-variant-numeric:tabular-nums;
color:var(--ink-soft)}
.caret{color:var(--muted);font-size:11px;transition:transform .2s}
details[open] .caret{transform:rotate(90deg)}
.body{padding:4px 16px 20px 82px;display:flex;flex-direction:column;gap:14px}
.ev{border-left:2px solid var(--border-firm);padding-left:14px}
.ev-f{font-family:var(--mono);font-size:11px;letter-spacing:.06em;text-transform:uppercase;
color:var(--muted);margin-bottom:4px}
.ev-cmp{font-family:var(--mono);font-size:12.5px;display:flex;gap:10px;align-items:baseline;
flex-wrap:wrap}
.ev-cmp .arrow{color:var(--brass)}
.ev-n{font-size:12.5px;color:var(--ink-soft);margin-top:3px}
.meta{display:flex;gap:24px;flex-wrap:wrap;padding-top:12px;border-top:1px dashed var(--border);
font-family:var(--mono);font-size:11.5px;color:var(--muted)}
.meta b{display:block;color:var(--ink-soft);font-weight:500;margin-top:2px;word-break:break-all}
.hash{font-size:11px;line-height:1.7}
.theatre{background:var(--surface);border:1px solid var(--border);border-radius:12px;
box-shadow:var(--shadow);overflow:hidden}
.picker{display:flex;border-bottom:1px solid var(--border);overflow-x:auto}
.pick{flex:1 0 auto;min-width:158px;padding:12px 16px;background:none;border:none;
border-bottom:2px solid transparent;cursor:pointer;text-align:left;font-family:var(--sans);
color:var(--muted)}
.pick:hover{background:var(--raised);color:var(--ink)}
.pick[aria-selected="true"]{color:var(--ink);border-bottom-color:var(--dot)}
.pick-t{font-family:var(--mono);font-size:12px;font-weight:600;display:flex;align-items:center;
gap:7px}
.pick-t::before{content:"";width:7px;height:7px;border-radius:50%;background:var(--dot);flex:none}
.pick-s{font-size:11.5px;margin-top:3px}
.stage-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr)}
.pane{padding:20px 22px;min-width:0}
.pane+.pane{border-left:1px solid var(--border)}
.pane-h{font-family:var(--mono);font-size:10.5px;letter-spacing:.09em;text-transform:uppercase;
color:var(--muted);margin-bottom:12px;display:flex;align-items:center;gap:8px}
.step-n{width:17px;height:17px;border-radius:50%;background:var(--brass-soft);color:var(--brass);
display:grid;place-items:center;font-size:10px;font-weight:600;flex:none}
pre{font-family:var(--mono);font-size:11.5px;line-height:1.6;background:var(--raised);
border:1px solid var(--border);border-radius:7px;padding:12px 14px;margin:0;max-height:250px;
overflow:auto;white-space:pre-wrap;word-break:break-word;color:var(--ink-soft)}
pre mark{background:color-mix(in srgb,var(--crit) 24%,transparent);color:var(--ink);
border-radius:2px;padding:0 2px}
.credit-line{font-family:var(--mono);font-size:20px;font-weight:600;
font-variant-numeric:tabular-nums;margin-bottom:2px}
.credit-sub{font-family:var(--mono);font-size:11.5px;color:var(--muted);word-break:break-all;
margin-bottom:14px}
.pool{display:flex;flex-direction:column;gap:5px}
.pool-r{display:grid;grid-template-columns:auto 1fr auto;gap:10px;align-items:baseline;
font-family:var(--mono);font-size:11.5px;padding:5px 9px;border-radius:5px;
background:var(--raised)}
.pool-r span{color:var(--muted);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.pool-more{font-family:var(--mono);font-size:11px;color:var(--muted);padding:3px 9px}
.gates{display:flex;flex-direction:column;gap:8px}
.gate{display:grid;grid-template-columns:26px 1fr;gap:12px;padding:11px 13px;
border:1px solid var(--border);border-radius:8px;background:var(--raised);opacity:.34;
transition:opacity .3s,border-color .3s,background .3s}
.gate.on{opacity:1}.gate.pass{border-color:var(--ok)}
.gate.fail{border-color:var(--crit);background:color-mix(in srgb,var(--crit) 9%,transparent)}
.gate.skip{opacity:.26}
.mk{width:26px;height:26px;border-radius:50%;display:grid;place-items:center;font-size:13px;
font-weight:700;border:1.5px solid var(--border-firm);color:var(--muted)}
.gate.pass .mk{border-color:var(--ok);color:var(--ok)}
.gate.fail .mk{border-color:var(--crit);color:var(--crit)}
.gate-n{font-family:var(--mono);font-size:12px;font-weight:600}
.gate-d{font-size:12.5px;color:var(--muted);margin-top:3px}
.gate.fail .gate-d{color:var(--crit)}
.verdict{margin-top:16px;padding:14px 16px;border-radius:8px;font-family:var(--mono);
display:flex;align-items:center;gap:12px;flex-wrap:wrap;border:1px solid var(--vc);
background:color-mix(in srgb,var(--vc) 12%,transparent)}
.verdict b{font-size:13px;font-weight:600;color:var(--vc)}
.verdict span{font-family:var(--sans);font-size:12.5px;color:var(--ink-soft)}
.runbar{display:flex;align-items:center;gap:12px;padding:12px 22px;
border-top:1px solid var(--border);background:var(--raised);flex-wrap:wrap}
.run{font-size:13px;font-weight:600;padding:8px 20px;border-radius:7px;
border:1px solid var(--ink);background:var(--ink);color:var(--ground);cursor:pointer}
.run:hover{opacity:.85}
.runnote{font-family:var(--mono);font-size:11.5px;color:var(--muted)}
.tag-scripted{font-family:var(--mono);font-size:10px;padding:2px 7px;border-radius:4px;
border:1px dashed var(--border-firm);color:var(--muted)}
.foot{border-top:1px solid var(--border);padding-top:18px;color:var(--muted);font-size:12.5px}
.foot code{font-family:var(--mono);color:var(--ink-soft)}
@media (max-width:860px){.stage-grid{grid-template-columns:1fr}
.pane+.pane{border-left:none;border-top:1px solid var(--border)}}
@media (max-width:720px){.wrap{padding:0 18px 64px}
summary{grid-template-columns:56px 1fr auto;gap:10px}.conf{display:none}.body{padding-left:18px}}
@media (prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}
"""


_JS = r"""
var VC={POSTED:"var(--ok)",AMOUNT_BEYOND_TOLERANCE:"var(--warn)",
LLM_INVALID_OUTPUT:"var(--crit)",LOW_CONFIDENCE:"var(--warn)"};
var BLURB=__BLURB__;
var GL={schema:"Schema",membership:"Membership",arithmetic:"Arithmetic",confidence:"Confidence"};
var GW=__GW__;
var ALL=["schema","membership","arithmetic","confidence"];
var sel=0,timer=null;
function money(p){var s=(p/100).toFixed(2),a=s.split("."),i=a[0],d=a[1];
var l=i.slice(-3),r=i.slice(0,-3);
return "₹"+(r?r.replace(/\B(?=(\d{2})+(?!\d))/g,",")+",":"")+l+"."+d;}
function e2(s){return String(s).replace(/[&<>]/g,function(m){
return {"&":"&amp;","<":"&lt;",">":"&gt;"}[m];});}
var picker=document.getElementById("picker");
if(picker&&CASES.length){
picker.innerHTML=CASES.map(function(c,i){
 var sub=c.verdict==="POSTED"?"posted":
  c.verdict==="AMOUNT_BEYOND_TOLERANCE"?"rejected · arithmetic":
  (c.stages.length>1?"rejected · membership":"rejected · schema");
 return '<button class="pick" role="tab" aria-selected="'+(i===0)+'" data-i="'+i+'" '+
  'style="--dot:'+VC[c.verdict]+'"><div class="pick-t">'+e2(c.txn)+
  (c.scripted?' <span class="tag-scripted">scripted</span>':'')+'</div>'+
  '<div class="pick-s">'+sub+'</div></button>';}).join("");
function drawGates(upto){var c=CASES[sel];
document.getElementById("gates").innerHTML=ALL.map(function(g,i){
 var st=null,k;for(k=0;k<c.stages.length;k++){if(c.stages[k].gate===g){st=c.stages[k];break;}}
 var reached=st&&i<=upto;
 var cls=!reached?(st?"":"skip"):(st.ok?"pass":"fail");
 var mark=!reached?String(i+1):(st.ok?"✓":"✕");
 var why=(reached&&st.why)?st.why:GW[g];
 return '<div class="gate '+(reached?"on ":"")+cls+'"><div class="mk">'+mark+'</div>'+
  '<div><div class="gate-n">'+GL[g]+'</div><div class="gate-d">'+e2(why)+
  '</div></div></div>';}).join("");}
function showVerdict(){var c=CASES[sel];
document.getElementById("verdict").innerHTML='<div class="verdict" style="--vc:'+
 VC[c.verdict]+'"><b>'+e2(c.verdict)+'</b><span>'+e2(BLURB[c.verdict]||"")+'</span></div>';
document.getElementById("run").textContent="Run again";}
function render(){var c=CASES[sel],picks=document.querySelectorAll(".pick"),i;
for(i=0;i<picks.length;i++)picks[i].setAttribute("aria-selected",i===sel);
document.getElementById("credit").innerHTML='<div class="credit-line">'+money(c.credit)+
 '</div><div class="credit-sub">'+e2(c.txn)+' · '+e2(c.date)+' · '+
 e2(c.narration)+'</div><div class="pool">'+c.cands.map(function(x){
  return '<div class="pool-r"><b>'+e2(x.id)+'</b><span>'+e2(x.cust)+'</span><b>'+
   money(x.gross)+'</b></div>';}).join("")+
 (c.n>c.cands.length?'<div class="pool-more">+ '+(c.n-c.cands.length)+
  ' more candidates ranked and sent</div>':'')+'</div>';
document.getElementById("prompt").textContent=c.prompt;
var raw=e2(c.raw);
for(var k=0;k<c.stages.length;k++){var s=c.stages[k];
 if(!s.ok&&s.gate==="membership"&&s.why){raw=raw;}}
document.getElementById("raw").innerHTML=raw;
drawGates(-1);document.getElementById("verdict").innerHTML="";
document.getElementById("run").textContent="Run the gates";}
function play(){clearInterval(timer);var c=CASES[sel],i=0;
document.getElementById("verdict").innerHTML="";drawGates(-1);
if(matchMedia("(prefers-reduced-motion: reduce)").matches){
 drawGates(c.stages.length-1);showVerdict();return;}
var step=function(){drawGates(i);
 if(i>=c.stages.length-1){clearInterval(timer);showVerdict();}i++;};
step();timer=setInterval(step,640);}
picker.addEventListener("click",function(ev){var b=ev.target.closest(".pick");if(!b)return;
clearInterval(timer);sel=+b.dataset.i;render();});
document.getElementById("run").addEventListener("click",play);
render();}
var filters=document.getElementById("filters");
if(filters){var rows=document.querySelectorAll("details.prov");
filters.innerHTML=["All tiers","T0","T1","T2","T3"].map(function(l,i){
 return '<button class="chip" aria-pressed="'+(i===0)+'" data-t="'+(i-1)+'">'+l+
  '</button>';}).join("");
filters.addEventListener("click",function(ev){var b=ev.target.closest(".chip");if(!b)return;
var chips=document.querySelectorAll(".chip"),i;
for(i=0;i<chips.length;i++)chips[i].setAttribute("aria-pressed","false");
b.setAttribute("aria-pressed","true");var t=+b.dataset.t;
for(i=0;i<rows.length;i++){var tag=rows[i].querySelector(".tier").textContent;
 rows[i].hidden=(t>=0&&tag!=="T"+t);}});}
"""

_JS = _JS.replace("__BLURB__", json.dumps(VERDICT_BLURB)).replace(
    "__GW__", json.dumps(GATE_QUESTION)
)
